### ISSUE TITLE
Error popup at startup on Linux platform

### ISSUE THREAD

**Issue by cp-api** [pdulth/capella-issues-test#11]
java.lang.ArrayIndexOutOfBoundsException: 1
    at org.polarsys.capella.core.platform.sirius.ui.navigator.view.CapellaCommonNavigator$CapellaFilteredTree.updateToolbar(CapellaCommonNavigator.java:419)
    at org.polarsys.capella.common.ui.toolkit.widgets.filter.FilteredTree$6.runInUIThread(FilteredTree.java:570)
    at org.eclipse.ui.progress.UIJob$1.run(UIJob.java:95)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3537)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3189)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.polarsys.capella.core.platform.sirius.ui.app.CapellaApplication.start(CapellaApplication.java:110)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1414)

`ECLIPSE-555491` `POLARSYS-83` `@sbo` `2014-12-04`

**Comment by cp-api** [comment]
**jba** commented on 2014-12-05
> Change-Id: [Ib302a9c4133363ca55bb4d1167bcdcf75eb1952e](https://github.com/search?q=Ib302a9c4133363ca55bb4d1167bcdcf75eb1952e&type=Commits)

**lre** commented on 2014-12-17
> This problem has just been fixed on master branch (not on v0.8.x branch). Is is normal?

**jba** commented on 2014-12-18
> It could be backported on v0.8.x branch, if you need it.

**lre** commented on 2014-12-18
> Yes, I think it is important to backport it for the next RC because all Linux users have this problem at the launch of Capella.

**jba** commented on 2014-12-18
> Cloned as bug #108 to backport for v0.8.x branch.
