### ISSUE TITLE
Error popup at startup on Linux platform

### ISSUE THREAD

**Issue by cp-api** [pdulth/capella-issues-test#28]
+++ This bug was initially created as a clone of Bug #83 +++

java.lang.ArrayIndexOutOfBoundsException: 1
    at org.polarsys.capella.core.platform.sirius.ui.navigator.view.CapellaCommonNavigator$CapellaFilteredTree.updateToolbar(CapellaCommonNavigator.java:419)
    at org.polarsys.capella.common.ui.toolkit.widgets.filter.FilteredTree$6.runInUIThread(FilteredTree.java:570)
    at org.eclipse.ui.progress.UIJob$1.run(UIJob.java:95)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3537)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3189)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.polarsys.capella.core.platform.sirius.ui.app.CapellaApplication.start(CapellaApplication.java:110)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1414)

`ECLIPSE-555494` `POLARSYS-108` `@jba` `2014-12-18`

**Comment by cp-api** [comment]
**jba** commented on 2014-12-18
> backport to v0.8.x branch

**lre** commented on 2015-01-09
> A gerrit is available here: https://polarsys.org/r/413
 > 
 > This is a cherry-pick of [POLARSYS-83](https://github.com/search?q=POLARSYS-83&type=Issues).

**lre** commented on 2015-01-09
> Gerrit has been merged (commit 423746f).
