### ISSUE TITLE
Information View errors on invalid BasicDiagnostic

### ISSUE THREAD

**Issue by pdulth** [pdulth/capella-issues-test#65]
when a log is created with a simple message (not an EmbeddedMessage), an error is raised.

java.lang.NullPointerException
	at org.polarsys.capella.common.tools.report.appenders.reportlogview.LightMarkerRegistry.createMarker(LightMarkerRegistry.java:133)
	at org.polarsys.capella.common.tools.report.appenders.reportlogview.LightMarkerRegistry.createMarker(LightMarkerRegistry.java:209)
	at org.polarsys.capella.common.tools.report.appenders.reportlogview.LightMarkerRegistry.createMarker(LightMarkerRegistry.java:205)
	at org.polarsys.capella.common.tools.report.appenders.reportlogview.ReportManagerLogViewAppender.report(ReportManagerLogViewAppender.java:148)
	at org.polarsys.capella.common.tools.report.appenders.reportlogview.ReportManagerLogViewAppender.report(ReportManagerLogViewAppender.java:170)
	at org.polarsys.capella.common.tools.report.appenders.reportlogview.ReportManagerLogViewAppender.append(ReportManagerLogViewAppender.java:67)

`ECLIPSE-555501` `POLARSYS-179` `@pdu` `2015-02-02`

**Comment by pdulth** [comment]
**pdu** commented on 2015-02-03
> Change-Id: [I68d6b6a9680bc6b3aaf3e025fd7a5ad820e7c555](https://github.com/search?q=I68d6b6a9680bc6b3aaf3e025fd7a5ad820e7c555&type=Commits)

**pdu** commented on 2015-02-03
> Additional gerrit:
 > Change-Id: [I53a144bdc4139329c68710812d50d8cdd65ea0c5](https://github.com/search?q=I53a144bdc4139329c68710812d50d8cdd65ea0c5&type=Commits)
