### ISSUE TITLE
Error on close session

### ISSUE THREAD

**Issue by pdulth** [pdulth/capella-issues-test#68]
An error occurs while closing session.

Message "The program was not able close the session" is generated in Error Log with the following stacktrace:

Caused by: java.lang.NullPointerException
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.rollback(AbstractTransactionalCommandStack.java:77)
	at org.polarsys.capella.common.platform.sirius.ted.SemanticEditingDomainFactory$SemanticCommandStack.executeNonDirtyingCommand(SemanticEditingDomainFactory.java:252)
	at org.polarsys.capella.common.platform.sirius.ted.SemanticEditingDomainFactory$SemanticCommandStack.doExecute(SemanticEditingDomainFactory.java:309)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:165)
	at org.polarsys.capella.common.ef.ExecutionManager.executeReadWriteCommand(ExecutionManager.java:91)
	at org.polarsys.capella.common.ef.ExecutionManager.execute(ExecutionManager.java:66)
	at org.polarsys.capella.core.sirius.ui.actions.CloseSessionAction$CloseSessionOperation.run(CloseSessionAction.java:178)

`ECLIPSE-553995` `POLARSYS-183` `@pdu` `2015-02-04`

**Comment by pdulth** [comment]
**pdu** commented on 2015-02-04
> The backport of [165] has introduced this error since we have introduced the super.dispose() in the ted.dispose() as it supposed to be.
 > This super.dispose() leads to inconsistencies since session's close through CloseSessionCommand is called into a transaction.
 > 
 > Since refactoring of CloseSessionCommand leads to major modifications, the super.dispose() call will be drived with a new ticket and not treated in 0.8.1.

**pdu** commented on 2015-02-10
> Change-Id: [Ie1fa0278465f0736f1bbfc5741dafb2d31a063fe](https://github.com/search?q=Ie1fa0278465f0736f1bbfc5741dafb2d31a063fe&type=Commits)
